services:
  web:
    build: .
    command: bash -c "service cron start && python manage.py runserver 0.0.0.0:8000"
    container_name: ccm-py
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8021:8000"
    networks:
      - ccm_net

networks:
  ccm_net:
    external: true
    name: ccm-net

