services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: ccm-py
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8021:8000"